import type { RecommendedWord } from '../types';

export const WORD_DATABASE: RecommendedWord[] = [
  // Technology
  { word: 'algorithm', definition: 'A set of rules for solving a problem in a finite number of steps', definitionJa: '有限の手順で問題を解くための規則の集合', example: 'The sorting algorithm runs in O(n log n) time.', categories: ['technology'] },
  { word: 'bandwidth', definition: 'The maximum rate of data transfer across a network', definitionJa: 'ネットワークを通じた最大データ転送速度', example: 'Streaming video requires high bandwidth.', categories: ['technology'] },
  { word: 'cache', definition: 'A hardware or software component that stores data to serve future requests faster', definitionJa: '将来のリクエストを高速化するためにデータを保存するコンポーネント', example: 'The browser cache stores web page resources locally.', categories: ['technology'] },
  { word: 'deploy', definition: 'To install and configure software for use in a production environment', definitionJa: 'ソフトウェアを本番環境で使用できるようインストールすること', example: 'We will deploy the new version tonight.', categories: ['technology'] },
  { word: 'encrypt', definition: 'To convert information into a coded form to prevent unauthorized access', definitionJa: '不正アクセスを防ぐために情報を暗号化すること', example: 'All passwords are encrypted before storage.', categories: ['technology'] },
  { word: 'firmware', definition: 'Permanent software programmed into a read-only memory', definitionJa: '読み取り専用メモリに組み込まれた永続的なソフトウェア', example: 'Update the router firmware to fix security issues.', categories: ['technology'] },
  { word: 'iterate', definition: 'To repeat a process in software development to refine the result', definitionJa: '結果を改善するためにプロセスを繰り返すこと', example: 'We need to iterate on the design based on user feedback.', categories: ['technology'] },
  { word: 'latency', definition: 'The delay before data transfer begins following an instruction', definitionJa: '指示後にデータ転送が開始するまでの遅延', example: 'High latency makes online gaming frustrating.', categories: ['technology'] },
  { word: 'malware', definition: 'Software designed to disrupt, damage, or gain unauthorized access to a computer', definitionJa: 'コンピュータを破壊したり不正アクセスするために設計されたソフト', example: 'The malware was hidden in an email attachment.', categories: ['technology'] },
  { word: 'protocol', definition: 'A set of rules governing the exchange of data between devices', definitionJa: 'デバイス間のデータ交換を規定するルールの集合', example: 'HTTP is the protocol for web communication.', categories: ['technology'] },
  { word: 'repository', definition: 'A storage location for software packages and source code', definitionJa: 'ソフトウェアパッケージやソースコードの保管場所', example: 'Push your changes to the remote repository.', categories: ['technology'] },
  { word: 'syntax', definition: 'The set of rules that defines the structure of a programming language', definitionJa: 'プログラミング言語の構造を定義するルールの集合', example: 'A syntax error will prevent the program from running.', categories: ['technology'] },
  { word: 'validate', definition: 'To check that data conforms to defined rules or constraints', definitionJa: 'データが定義されたルールや制約に適合するか確認すること', example: 'Always validate user input before processing.', categories: ['technology'] },
  { word: 'debug', definition: 'To find and remove errors from a computer program', definitionJa: 'コンピュータプログラムのエラーを見つけて取り除くこと', example: 'She spent hours debugging the authentication module.', categories: ['technology'] },
  { word: 'framework', definition: 'A reusable set of libraries and tools for building software applications', definitionJa: 'ソフトウェアアプリを構築するための再利用可能なライブラリとツールの集合', example: 'React is a popular frontend framework.', categories: ['technology'] },

  // Law
  { word: 'acquit', definition: 'To formally declare someone not guilty of a criminal charge', definitionJa: '刑事告訴に対して無罪を正式に宣言すること', example: 'The jury acquitted the defendant due to lack of evidence.', categories: ['law'] },
  { word: 'affidavit', definition: 'A written statement confirmed by oath for use as evidence in court', definitionJa: '法廷での証拠として使用するための宣誓書付き書面陳述', example: 'She submitted an affidavit describing what she witnessed.', categories: ['law'] },
  { word: 'arbitration', definition: 'A process of resolving disputes outside court using a neutral third party', definitionJa: '中立な第三者を使った裁判外の紛争解決プロセス', example: 'The labor dispute was settled through binding arbitration.', categories: ['law'] },
  { word: 'defendant', definition: 'An individual or entity being sued or accused in a court of law', definitionJa: '法廷で訴訟または訴追されている個人または組織', example: 'The defendant pleaded not guilty to all charges.', categories: ['law'] },
  { word: 'felony', definition: 'A serious crime punishable by imprisonment of more than one year', definitionJa: '1年以上の禁固刑に処せられる重大犯罪', example: 'Armed robbery is a felony in all jurisdictions.', categories: ['law'] },
  { word: 'injunction', definition: 'A court order requiring a party to do or stop doing a specific act', definitionJa: '当事者に特定の行為の実行または停止を命じる裁判所命令', example: 'The court issued an injunction against the construction project.', categories: ['law'] },
  { word: 'jurisdiction', definition: 'The official power to make legal decisions within a defined area', definitionJa: '定義された地域内で法的決定を下す公式権限', example: 'This case falls outside the jurisdiction of the local court.', categories: ['law'] },
  { word: 'litigation', definition: 'The process of taking legal action through the court system', definitionJa: '裁判制度を通じて法的措置をとるプロセス', example: 'The company wanted to avoid costly litigation.', categories: ['law'] },
  { word: 'negligence', definition: 'Failure to take proper care resulting in damage or injury to another', definitionJa: '適切なケアを怠り、他者に損害や傷害を与えること', example: 'The hospital was sued for medical negligence.', categories: ['law'] },
  { word: 'plaintiff', definition: 'A person who brings a case against another in a court of law', definitionJa: '法廷で他者に対して訴訟を起こす人', example: 'The plaintiff is seeking compensation for damages.', categories: ['law'] },
  { word: 'subpoena', definition: 'A writ ordering a person to attend court or produce documents', definitionJa: '人物に出廷または文書提出を命じる令状', example: 'The witness received a subpoena to testify at the trial.', categories: ['law'] },
  { word: 'testimony', definition: 'A formal statement given by a witness under oath in a court', definitionJa: '証人が法廷で宣誓のもと行う正式な陳述', example: 'Her eyewitness testimony was crucial to the case.', categories: ['law'] },
  { word: 'verdict', definition: 'A decision on an issue in a civil or criminal case', definitionJa: '民事または刑事事件における問題の決定', example: 'The jury returned a verdict of guilty.', categories: ['law'] },
  { word: 'statute', definition: 'A written law passed by a legislative body', definitionJa: '立法機関によって可決された成文法', example: 'The statute of limitations expired after three years.', categories: ['law'] },
  { word: 'tort', definition: 'A wrongful act leading to civil legal liability', definitionJa: '民事的な法的責任につながる不法行為', example: 'Personal injury falls under tort law.', categories: ['law'] },

  // Literature
  { word: 'allegory', definition: 'A story with a hidden meaning, typically a moral or political one', definitionJa: '道徳的または政治的な隠された意味を持つ物語', example: 'Animal Farm is an allegory for the Russian Revolution.', categories: ['literature'] },
  { word: 'alliteration', definition: 'Repetition of the same consonant sound at the start of nearby words', definitionJa: '近くの単語の冒頭に同じ子音の音を繰り返すこと', example: '"Peter Piper picked a peck" is an example of alliteration.', categories: ['literature'] },
  { word: 'antagonist', definition: 'A character who actively opposes the protagonist in a story', definitionJa: '物語の主人公に積極的に反対するキャラクター', example: 'Iago is the antagonist in Shakespeare\'s Othello.', categories: ['literature'] },
  { word: 'catharsis', definition: 'Emotional release or purification experienced through art or drama', definitionJa: '芸術や演劇を通じて経験する感情の解放または浄化', example: 'The tragic ending provided catharsis for the audience.', categories: ['literature'] },
  { word: 'denouement', definition: 'The final part of a story where conflicts are resolved', definitionJa: '物語の終盤で対立が解決される部分', example: 'The denouement revealed that the butler was the murderer.', categories: ['literature'] },
  { word: 'foreshadowing', definition: 'A literary device that hints at what will happen later in the story', definitionJa: '物語の後で起こることを示唆する文学的手法', example: 'The dark clouds foreshadowed the coming conflict.', categories: ['literature'] },
  { word: 'irony', definition: 'Expression of meaning using language that normally signals the opposite', definitionJa: '通常は逆の意味を示す言語を使って意味を表現すること', example: 'The fire station burning down is an example of situational irony.', categories: ['literature'] },
  { word: 'metaphor', definition: 'A figure of speech describing something as something else to suggest similarity', definitionJa: '類似性を示唆するためにある物を別の物として描写する比喩表現', example: '"Life is a journey" is a common metaphor.', categories: ['literature'] },
  { word: 'motif', definition: 'A recurring element that has symbolic significance in a story', definitionJa: '物語の中で象徴的な意味を持つ繰り返し出てくる要素', example: 'Water is a motif symbolizing renewal throughout the novel.', categories: ['literature'] },
  { word: 'protagonist', definition: 'The leading character in a play, film, or novel', definitionJa: '演劇、映画、小説の主人公', example: 'Harry Potter is the protagonist of the series.', categories: ['literature'] },
  { word: 'soliloquy', definition: 'A speech in a play where a character speaks to themselves aloud', definitionJa: '演劇でキャラクターが独り言を言うシーン', example: '"To be or not to be" is Hamlet\'s famous soliloquy.', categories: ['literature'] },
  { word: 'rhetoric', definition: 'The art of effective or persuasive speaking and writing', definitionJa: '効果的または説得力のある話し方・書き方の技術', example: 'The politician used powerful rhetoric in his speech.', categories: ['literature', 'academic'] },
  { word: 'elegy', definition: 'A mournful poem or song lamenting the dead', definitionJa: '死者を悼む哀悼の詩や歌', example: 'Gray\'s "Elegy Written in a Country Churchyard" is a classic.', categories: ['literature'] },
  { word: 'juxtaposition', definition: 'Placing two contrasting things side by side for effect', definitionJa: '効果のために対照的な2つのものを並べること', example: 'The juxtaposition of wealth and poverty is central to the theme.', categories: ['literature', 'academic'] },

  // Medicine
  { word: 'acute', definition: 'Describing a condition with rapid onset and severe symptoms', definitionJa: '急速な発症と重篤な症状を持つ状態を表す', example: 'He was treated for acute appendicitis.', categories: ['medicine'] },
  { word: 'benign', definition: 'Not harmful; used to describe a tumor that is not cancerous', definitionJa: '無害な；がん性でない腫瘍を表すのに使用', example: 'The biopsy showed the growth was benign.', categories: ['medicine'] },
  { word: 'chronic', definition: 'Persisting for a long time or constantly recurring', definitionJa: '長期間持続または繰り返す', example: 'She manages her chronic back pain with physical therapy.', categories: ['medicine'] },
  { word: 'diagnosis', definition: 'The identification of the nature of an illness through examination', definitionJa: '検査による病気の性質の識別', example: 'Early diagnosis greatly improves treatment outcomes.', categories: ['medicine'] },
  { word: 'epidemic', definition: 'A widespread occurrence of an infectious disease in a community', definitionJa: 'コミュニティでの感染症の広範な発生', example: 'The flu epidemic affected millions this winter.', categories: ['medicine', 'science'] },
  { word: 'hypertension', definition: 'Abnormally high blood pressure in the arteries', definitionJa: '動脈内の異常に高い血圧', example: 'Reducing sodium intake can help control hypertension.', categories: ['medicine'] },
  { word: 'malignant', definition: 'Tending to grow and spread rapidly; cancerous', definitionJa: '急速に増殖・拡大する傾向がある；がん性の', example: 'The tumor was found to be malignant.', categories: ['medicine'] },
  { word: 'pathology', definition: 'The scientific study of disease processes and their effects', definitionJa: '疾病プロセスとその影響の科学的研究', example: 'The pathology report confirmed the diagnosis.', categories: ['medicine', 'science'] },
  { word: 'prognosis', definition: 'A forecast of the likely course and outcome of a disease', definitionJa: '病気の経過と結果の予測', example: 'The prognosis for recovery is excellent.', categories: ['medicine'] },
  { word: 'symptom', definition: 'A sign of the existence of a disease or problem experienced by the patient', definitionJa: '患者が経験する病気や問題の存在のサイン', example: 'Fever is a common symptom of infection.', categories: ['medicine'] },
  { word: 'vaccine', definition: 'A biological preparation that provides active acquired immunity to disease', definitionJa: '疾患に対する能動的な後天性免疫を提供する生物学的製剤', example: 'The vaccine was developed in record time.', categories: ['medicine', 'science'] },
  { word: 'remission', definition: 'A diminution of the symptoms of a disease; temporary recovery', definitionJa: '病気の症状の軽減；一時的な回復', example: 'The cancer has been in complete remission for five years.', categories: ['medicine'] },
  { word: 'inflammation', definition: 'Redness, swelling and pain caused by the body\'s response to injury or infection', definitionJa: '傷害や感染に対する身体の反応による赤み、腫れ、痛み', example: 'Ice can reduce inflammation after an injury.', categories: ['medicine'] },

  // Business/Finance
  { word: 'acquisition', definition: 'The purchase of one company by another', definitionJa: 'ある会社による別の会社の購入', example: 'The tech giant announced the acquisition of its rival.', categories: ['business'] },
  { word: 'amortize', definition: 'To gradually write off the initial cost of an asset over a period', definitionJa: '資産の初期費用を期間をかけて徐々に償却すること', example: 'They plan to amortize the cost over ten years.', categories: ['business'] },
  { word: 'collateral', definition: 'An asset pledged as security for repayment of a loan', definitionJa: 'ローン返済の担保として差し出される資産', example: 'The house was used as collateral for the business loan.', categories: ['business'] },
  { word: 'dividend', definition: 'A sum of money paid regularly to shareholders from a company\'s profits', definitionJa: '会社の利益から株主に定期的に支払われる金額', example: 'Investors receive quarterly dividends.', categories: ['business'] },
  { word: 'equity', definition: 'The value of shares issued by a company; ownership interest', definitionJa: '会社が発行した株式の価値；所有権の持分', example: 'She owns 30% equity in the startup.', categories: ['business'] },
  { word: 'leverage', definition: 'Using borrowed capital to increase potential return of an investment', definitionJa: '投資の潜在的なリターンを高めるために借入資本を使用すること', example: 'The company used financial leverage to fund its expansion.', categories: ['business'] },
  { word: 'liquidation', definition: 'The process of converting assets to cash, especially in bankruptcy', definitionJa: '資産を現金に変換するプロセス、特に倒産時', example: 'The company went into liquidation after its debts became unmanageable.', categories: ['business'] },
  { word: 'merger', definition: 'A combination of two companies into one new entity', definitionJa: '2つの会社を1つの新しい組織に合併すること', example: 'The merger created the world\'s largest airline.', categories: ['business'] },
  { word: 'portfolio', definition: 'A range of investments held by a person or organization', definitionJa: '個人または組織が保有する投資の範囲', example: 'She diversified her investment portfolio to reduce risk.', categories: ['business'] },
  { word: 'revenue', definition: 'Income generated from normal business operations', definitionJa: '通常の事業運営から生成された収入', example: 'Total revenue increased by 15% this quarter.', categories: ['business'] },
  { word: 'subsidy', definition: 'Money granted by the government to help an industry or business', definitionJa: '産業や企業を支援するために政府が付与する資金', example: 'The agricultural sector relies on government subsidies.', categories: ['business'] },
  { word: 'valuation', definition: 'The estimation of the worth of something, especially a company', definitionJa: '何か、特に会社の価値の推定', example: 'The startup\'s valuation reached $1 billion.', categories: ['business'] },
  { word: 'depreciation', definition: 'A reduction in value of an asset over time due to wear and tear', definitionJa: '摩耗などにより時間の経過とともに資産価値が下がること', example: 'The car depreciated quickly in its first year.', categories: ['business'] },

  // Science
  { word: 'catalyst', definition: 'A substance that increases the rate of a chemical reaction without being consumed', definitionJa: '消費されずに化学反応速度を高める物質', example: 'Enzymes act as catalysts in biological reactions.', categories: ['science'] },
  { word: 'entropy', definition: 'A measure of disorder or randomness in a system', definitionJa: 'システム内の無秩序またはランダム性の尺度', example: 'According to the second law, entropy always increases.', categories: ['science'] },
  { word: 'hypothesis', definition: 'A proposed explanation for an observation that can be tested', definitionJa: 'テスト可能な観察に対する提案された説明', example: 'The scientist formulated a hypothesis before conducting the experiment.', categories: ['science', 'academic'] },
  { word: 'molecule', definition: 'The smallest unit of a substance that retains its chemical properties', definitionJa: 'その化学的性質を保持する物質の最小単位', example: 'A water molecule consists of two hydrogen atoms and one oxygen atom.', categories: ['science'] },
  { word: 'osmosis', definition: 'Movement of molecules through a membrane from high to low concentration', definitionJa: '高濃度から低濃度への膜を通した分子の移動', example: 'Plants absorb water through osmosis.', categories: ['science'] },
  { word: 'quantum', definition: 'The minimum discrete amount of a physical quantity', definitionJa: '物理量の最小離散量', example: 'Quantum mechanics describes behavior at the atomic scale.', categories: ['science'] },
  { word: 'synthesis', definition: 'The combination of elements to form a connected whole; chemical production', definitionJa: '要素を結合して統一されたものを形成すること；化学的生産', example: 'The synthesis of aspirin is a classic chemistry experiment.', categories: ['science', 'academic'] },
  { word: 'empirical', definition: 'Based on observation or experience rather than theory', definitionJa: '理論ではなく観察や経験に基づいた', example: 'The empirical evidence supported the theory.', categories: ['science', 'academic'] },
  { word: 'isotope', definition: 'One of two or more atoms of the same element with different neutron numbers', definitionJa: '中性子数が異なる同じ元素の原子', example: 'Carbon-14 is a radioactive isotope used in dating.', categories: ['science'] },
  { word: 'photosynthesis', definition: 'The process by which plants use sunlight to convert CO2 and water into energy', definitionJa: '植物が日光を使ってCO2と水をエネルギーに変換するプロセス', example: 'Photosynthesis produces oxygen as a byproduct.', categories: ['science'] },

  // Academic/General
  { word: 'ambiguous', definition: 'Open to more than one interpretation; not having one obvious meaning', definitionJa: '複数の解釈が可能；明確な意味が一つでない', example: 'The contract contained several ambiguous clauses.', categories: ['academic', 'general'] },
  { word: 'paradigm', definition: 'A typical example or model; a framework of thought', definitionJa: '典型的な例やモデル；思考の枠組み', example: 'The internet caused a paradigm shift in communication.', categories: ['academic'] },
  { word: 'mitigate', definition: 'To make less severe, serious, or painful', definitionJa: '深刻さ、重大さ、または痛みを軽減すること', example: 'We need to mitigate the risks before proceeding.', categories: ['academic', 'general'] },
  { word: 'substantiate', definition: 'To provide evidence to support or prove the truth of', definitionJa: '真実を支持または証明する証拠を提供すること', example: 'Can you substantiate that claim with data?', categories: ['academic'] },
  { word: 'enumerate', definition: 'To mention items one by one; to list', definitionJa: 'アイテムを一つずつ挙げること；リストにすること', example: 'Please enumerate the steps needed to complete the task.', categories: ['academic'] },
  { word: 'ephemeral', definition: 'Lasting for a very short time', definitionJa: 'ごく短い時間しか続かない', example: 'The ephemeral beauty of cherry blossoms is celebrated in Japan.', categories: ['general', 'literature'] },
  { word: 'pragmatic', definition: 'Dealing with things sensibly and realistically', definitionJa: '物事を賢明かつ現実的に扱うこと', example: 'We need a pragmatic approach to solve this problem.', categories: ['academic', 'general'] },
  { word: 'coherent', definition: 'Logical and consistent; forming a unified whole', definitionJa: '論理的で一貫した；統一された全体を形成する', example: 'Please present a coherent argument in your essay.', categories: ['academic', 'general'] },
  { word: 'ambivalent', definition: 'Having mixed feelings or uncertain views about something', definitionJa: '何かについて複雑な感情や不確かな見解を持つ', example: 'She felt ambivalent about moving to a new city.', categories: ['general'] },
  { word: 'eloquent', definition: 'Fluent and persuasive in speech or writing', definitionJa: '話し言葉や文章が流暢で説得力がある', example: 'He gave an eloquent speech at the graduation ceremony.', categories: ['general', 'literature'] },
  { word: 'meticulous', definition: 'Very careful and precise about details', definitionJa: '細部に非常に注意深く正確な', example: 'The surgeon was meticulous in her technique.', categories: ['general'] },
  { word: 'resilient', definition: 'Able to recover quickly from difficulties; tough', definitionJa: '困難からすぐに立ち直れる；タフな', example: 'Children are remarkably resilient.', categories: ['general'] },
  { word: 'verbose', definition: 'Using more words than needed; wordy', definitionJa: '必要以上の言葉を使う；冗長な', example: 'The report was too verbose and needed editing.', categories: ['general', 'literature'] },
  { word: 'nuance', definition: 'A subtle difference in meaning, expression, or sound', definitionJa: '意味、表現、または音の微妙な違い', example: 'Understanding cultural nuances takes time.', categories: ['general', 'academic'] },
  { word: 'perpetuate', definition: 'To make something continue indefinitely', definitionJa: '何かを無期限に続けること', example: 'Stereotypes are perpetuated by the media.', categories: ['general', 'academic'] },
];
